/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PlayerPuck(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/PlayerPuck.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.PlayerPuck.geometry}
        material={materials.PlayerPuck}
        position={[0, 0, 3.9]}
      />
    </group>
  )
}

useGLTF.preload('/models/PlayerPuck.glb')
