/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PlayArea(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/PlayArea.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlayArea.geometry}
        material={materials.Table}
        position={[0, -1, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/PlayArea.glb')
