/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Stage.glb')

materials.palette.emissiveIntensity = 0;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-10'].geometry}
        material={nodes['FullScene-10'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-11'].geometry}
        material={nodes['FullScene-11'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-12'].geometry}
        material={nodes['FullScene-12'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-13'].geometry}
        material={nodes['FullScene-13'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-14'].geometry}
        material={nodes['FullScene-14'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-15'].geometry}
        material={nodes['FullScene-15'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-16'].geometry}
        material={nodes['FullScene-16'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-17'].geometry}
        material={nodes['FullScene-17'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-18'].geometry}
        material={nodes['FullScene-18'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-19'].geometry}
        material={nodes['FullScene-19'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-20'].geometry}
        material={nodes['FullScene-20'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-21'].geometry}
        material={nodes['FullScene-21'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-22'].geometry}
        material={nodes['FullScene-22'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-23'].geometry}
        material={nodes['FullScene-23'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-24'].geometry}
        material={nodes['FullScene-24'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-25'].geometry}
        material={nodes['FullScene-25'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-26'].geometry}
        material={nodes['FullScene-26'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-27'].geometry}
        material={nodes['FullScene-27'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-28001'].geometry}
        material={nodes['FullScene-28001'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-28002'].geometry}
        material={nodes['FullScene-28002'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-28003'].geometry}
        material={nodes['FullScene-28003'].material}
        position={[-1.56, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-28004'].geometry}
        material={nodes['FullScene-28004'].material}
        position={[-3.11, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-28005'].geometry}
        material={nodes['FullScene-28005'].material}
        position={[-7.71, -3.5, -0.28]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-28006'].geometry}
        material={nodes['FullScene-28006'].material}
        position={[-9.27, -3.5, -0.28]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-5'].geometry}
        material={nodes['FullScene-5'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-6'].geometry}
        material={nodes['FullScene-6'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-7'].geometry}
        material={nodes['FullScene-7'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-8'].geometry}
        material={nodes['FullScene-8'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['FullScene-9'].geometry}
        material={nodes['FullScene-9'].material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ObjObject.geometry}
        material={nodes.ObjObject.material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ObjObject001.geometry}
        material={nodes.ObjObject001.material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ObjObject002.geometry}
        material={nodes.ObjObject002.material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ObjObject003.geometry}
        material={nodes.ObjObject003.material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ObjObject004.geometry}
        material={nodes.ObjObject004.material}
        position={[0, -3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.71, 0.71, 0.71]}
      />
    </group>
  )
}

useGLTF.preload('/models/Stage.glb')
